#!/usr/bin/env python3

# Takes on standard input an “unformatted” file. Expected format (yeah):
#     kanji     reading       meaning
# with random number of spaces between each
# If there is a `XXX:` (surrounded by spaces) in `meaning`, then what follows
# will be considered to be a note

# It writes on standard output a CSV file
# The output CSV has fields: (kanji, reading, meaning, notes)

# This is designed to be used on a hand-processed file generated by
#   pdftotext -layout
# Then hand-verification of `to_import.csv` looking good and finally import into
# Anki

import csv
import sys

out = csv.writer(sys.stdout)

for line in sys.stdin:
    line = line.split()
    if line == []:
        continue

    kanji = line[0]
    reading = line[1]

    line = line[2:]

    if 'XXX:' in line:
        idx = line.index('XXX:')
        meaning = ' '.join(line[:idx])
        notes = ' '.join(line[idx + 1:])
    else:
        meaning = ' '.join(line)
        notes = ''

    out.writerow([kanji, reading, meaning, notes])
